spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: projetos
          uri: lb://PROJETO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/projeto/**
        - id: tarefas
          uri: lb://TAREFA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/tarefa/**
        - id: logs
          uri: lb://LOG-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/log/**
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka/
